### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by Noobidoo**
Update for 1.19
Right now only compiles has not been tested.

Only some minor changes.

### CODE REVIEW

**Comment by Shirayo** [comment]
do not work even normal songs. Just black screen. I can choose custom tracks but play button does not work

**Comment by njhampsh** [comment]
if zenjector.Install<MPGameInstaller>(Location.MultiplayerCore); is changed to 
zenjector.Install<MPGameInstaller>(Location.GameCore);
or
zenjector.Install<MPGameInstaller>(Location.MultiPlayer);

the maps play without the black screen but the play button is still grayed out. If you select a standard song then back to custom song, then play the last standard selected song will play.

**Comment by dantdmsnr** [comment]
hi all first time talking on github but how do we get the dev buildings and can you pls update the mod to 1.19.0 pls
+

**Comment by NCSGeek** [comment]
> hi all first time talking on github but how do we get the dev buildings and can you pls update the mod to 1.19.0 pls +

This is a pull request, so if you wanted to get the dev build in question you could go to the fork and compile it. But I dont think that's what you are looking for

**Comment by mvinaround** [comment]
Hi, anyone actually got a working build yet?

**Comment by Huntershotz11** [comment]
Has anyone actually got this working yet????

**Comment by Goobwabber** [comment]
deprecated branch :C

**Comment by texic88** [comment]
just for everyone waiting till the update comes. there is an easy way to downgrade with BSlegacy. all my friends use it too
https://bslegacy.com/

**Comment by Goobwabber** [comment]
old

**Pull request closed without merging**
