### PR TITLE
1.18 Update

### PR DESCRIPTION
**Pull request by Goobwabber**
nice

### CODE REVIEW

**Comment by tjhorner** [comment]
Need any help with this? I'm glad to assist wherever I can

**Comment by xplodwild** [comment]
Same here, if there's anything I can do to help make this happen quicker, I'm all in!

**Comment by xplodwild** [comment]
@Goobwabber could you just update us if there's any unpushed code that you have locally, and if this is still being worked on? I'd love to contribute some code otherwise

**Comment by Goobwabber** [comment]
@xplodwild check message on the issue attached to this pr

**Comment by Goobwabber** [comment]
Right ok so almost ready for public C:

**Comment by deadperch** [comment]
We would love to test :)

**Comment by A-plou** [comment]
you probably need to update the README.md at some point.

**Comment by fbhijhifj** [comment]
When will it be ready?

**Comment by xplodwild** [comment]
> When will it be ready?

I tried to build and play the 1.16.3 branch (this PR), while everything *seems* fine, the "Start game" button remains greyed out with the text "No song selected" (although it displays as the next song at the top etc).
I tried to hack it to force the Start game button to be enabled, but after the countdown, nothing happens, so I guess I'm still missing something somewhere. It seems close to be ready though!

**Comment by qe201020335** [comment]
As stated in #146 by Goobie
> I ended up deleting all code related to making it work on official servers because it wasn't worth how buggy things would be. BeatTogether's dedicated servers are currently in testing phase and the new commits are made to work with those servers instead. Since the mod hasn't been publicly released I'm closing this issue.

Though, I can confirm that there is one commit, that you can build and works for both 1.17 and 1.18. (I have been using it with my friend for a month now.)

**Comment by Amyxox** [comment]
> As stated in #146 by Goobie
> 
> > I ended up deleting all code related to making it work on official servers because it wasn't worth how buggy things would be. BeatTogether's dedicated servers are currently in testing phase and the new commits are made to work with those servers instead. Since the mod hasn't been publicly released I'm closing this issue.
> 
> Though, I can confirm that there is one commit, that you can add a tiny fix and works for both 1.17 and 1.18. (I have been using it with my friend for a month now.)
> 
> HINT

How have you been playing it when it’s not released?

**Comment by qe201020335** [comment]
I built and tested it myself. If it's not working, when fix it enough so that it is usable. 

This being said, my build is only for private use since it is still a unfinished mod. Anything could go wrong. The way it tricks the official server to accept a custom level can make a mess when error happens.

**Comment by xplodwild** [comment]
Thanks @qe201020335! I used your fork and did "that change" (wink wink) to make it work and had a fun session with a friend. 
Makes me realize how much better the game is with custom songs :)

**Comment by robinbecx** [comment]
> is it almost done? sorry very excited

Same here

**Review by BillyBobJones678 — COMMENTED** [review]
You still working on it I see

**Comment by doug-cannon** [comment]
Is this Multiplayer Extension mod working for **Beat Saber 1.18.1**? The last time I've played, it was like on **version 1.16**. So I downloaded this and copied it into my **Plugins folder**, and it still would not work—just the default multiplayer.

**Comment by drcharlie92** [comment]
Any news on release date for this?

**Comment by drcharlie92** [comment]
@Goobwabber any news on this?

**Comment by Goobwabber** [comment]
nice

**Comment by gellis12** [comment]
Been waiting for this day for such a long time, thanks for all the hard work!

**Pull request merged**
