### PR TITLE
1.19.0 Update

### PR DESCRIPTION
**Pull request by herkolategan**
### Updates to accommodate a few small changes in dependencies

- **SongCore** no longer requires add song call
- **IPreviewBeatmapLevel** interface changes
- **Harmony** API change
- **Zenjector** API change

### Testing

- Tested locally and the mod starts and shows up in the UI / Multiplayer menu

#### Update

- **Tested a live multiplayer setup, but unfortunately it did not work. Keeping the PR in draft for now until I can pin down the issues in the logs.**

### CODE REVIEW

**Comment by herkolategan** [comment]
Found the issue in the logs, **ExtendedPlayerTableCell** needs to be updated; some new fields that are not present in the stub,

**Comment by NCSGeek** [comment]
Why has this been closed?

**Comment by blackfisch** [comment]
> Why has this been closed?

see description:
> Tested a live multiplayer setup, but unfortunately it did not work. Keeping the PR in draft for now until I can pin down the issues in the logs.

@herkolategan maybe this helps: https://github.com/Goobwabber/MultiplayerExtensions/issues/165#issuecomment-1013740036

**Comment by herkolategan** [comment]
@NCSGeek @blackfisch Apologies, I should have given a clearer reason for closing this PR. I had limited time to try and fix it. On the surface everything looked good, but as @blackfisch mentioned there are other more hidden problems. Lacking any prior knowledge of Beat Saber modding, it became a bigger problem than I anticipated.

**Pull request closed without merging**
